2023-02-21 11:14:39,153 ERROR: Exception on /services [GET] [in D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\app\main\routes.py", line 20, in services
    return render_template('services.html', title='Сервис', services=current_user.services1)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'services1'
2023-02-21 11:17:23,932 ERROR: Exception on /services [GET] [in D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\app\main\routes.py", line 20, in services
    return render_template('services.html', title='Сервис', services=current_user.services1)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'services1'
2023-02-21 11:21:35,789 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:69]
2023-02-21 11:25:10,452 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:69]
2023-02-21 11:25:23,110 ERROR: Exception on /services [GET] [in D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\app\main\routes.py", line 20, in services
    return render_template('services.html', title='Сервис', services=current_user.services1)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'services1'
2023-02-21 11:27:04,814 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:69]
2023-02-21 11:27:11,606 ERROR: Exception on /services [GET] [in D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm\daily_app\app\main\routes.py", line 20, in services
    return render_template('services.html', title='Сервис', services=current_user.services1)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'services1'
2023-02-21 11:29:03,549 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:69]
2023-02-21 11:29:05,183 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:69]
2023-02-21 11:47:59,175 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:13:38,082 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:13:39,499 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:24:03,741 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:30:58,677 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:35:36,870 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:36:02,155 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:44:16,804 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:44:56,957 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:45:23,024 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:45:49,832 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:45:58,756 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:46:13,691 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:46:58,361 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:47:18,853 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 12:47:42,533 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:07:35,038 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:08:58,764 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:09:08,425 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:09:25,227 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:10:10,932 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:12:35,547 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:13:13,226 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:16:46,513 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:19:49,796 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:20:23,346 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:20:29,262 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:27:04,995 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 13:28:43,166 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:09:38,141 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:09:44,302 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:09:46,044 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:10:47,993 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:11:38,770 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:13:53,003 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:15:42,903 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:15:58,686 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:16:48,011 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:18:47,214 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:23:28,576 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
2023-02-21 14:23:39,302 INFO: WorkWeek start [in D:\PyCharm\daily_app\app\__init__.py:72]
